superlists/accounts/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import logout

from accounts import views

urlpatterns = [
    url(r'^send_login_email$', views.send_login_email, name='send_login_email'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', logout, {'next_page': '/'}, name='logout'),

]

superlists/lists/urls.py
from django.conf.urls import url
from django.contrib import admin

from lists import views

urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(.+)/share$', views.share_list, name='share_list'),
    url(r'^users/(.+)/$', views.my_lists, name='my_lists'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
]

superlists/superlists/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from lists import urls as lists_urls
from lists import views as lists_views
from accounts import urls as accounts_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lists/', include(lists_urls)),
    url(r'^accounts/', include(accounts_urls)),
    url(r'^$', lists_views.home_page, name='home'),
]

superlists/accounts/models.py
import uuid

from django.contrib import auth
from django.db import models

auth.signals.user_logged_in.disconnect(auth.models.update_last_login)


class User(models.Model):
    """Модель пользователя"""

    email = models.EmailField(primary_key=True)
    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'
    is_anonymous = False
    is_authenticated = True


class Token(models.Model):
    """Модель токена для каждого пользователя"""

    email = models.EmailField()
    uid = models.CharField(max_length=255, default=uuid.uuid4)

superlists/lists/models.py
from django.conf import settings
from django.db import models

# Create your models here.
from django.urls import reverse


class List(models.Model):
    """модель списка"""

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    shared_with = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="available_lists")

    @property
    def name(self):
        return self.item_set.first().text

    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

    @staticmethod
    def create_new(first_item_text, owner=None):
        """Создать новый"""

        list_ = List.objects.create(owner=owner)
        Item.objects.create(text=first_item_text, list=list_)
        return list_


class Item(models.Model):
    """Элемент списка"""
    text = models.TextField(verbose_name='Текст', default='')
    list = models.ForeignKey(List, default=None)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ('id',)
        unique_together = ('text', 'list')

superlists/lists/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms.utils import ErrorList

from lists.models import Item, List

EMPTY_ITEM_ERROR = 'Элементы списка не должны быть пустыми'
DUPLICATE_ITEM_ERROR = 'Такой элемент уже присутствует в списке'


class ItemForm(forms.ModelForm):
    """форма для эелемента списка"""

    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.TextInput(attrs={
                'placeholder': 'Enter a to-do item',
                'class': 'form-control input-lg'
            })
        }
        error_messages = {
            'text': {'required': EMPTY_ITEM_ERROR}
        }


class ExistingListItemForm(ItemForm):
    """форма для эелемента существующего списка"""

    def __init__(self, data=None, files=None, auto_id='id_%s', prefix=None, initial=None, error_class=ErrorList,
                 label_suffix=None, empty_permitted=False, instance=None, use_required_attribute=None, for_list=None):
        super().__init__(data, files, auto_id, prefix, initial, error_class, label_suffix, empty_permitted, instance,
                         use_required_attribute)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)


class NewListForm(ItemForm):
    """форма нового списка"""

    def save(self, owner):
        if owner.is_authenticated:
            return List.create_new(first_item_text=self.cleaned_data['text'], owner=owner)
        else:
            return List.create_new(first_item_text=self.cleaned_data['text'])

superlists/accounts/views.py
from django.contrib import messages, auth
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse

from accounts.models import Token


def send_login_email(request):
    """отправка ссылки для входа на email"""

    email = request.POST['email']
    token = Token.objects.create(email=email)
    url = request.build_absolute_uri(
        reverse('login') + '?token=' + str(token.uid)
    )
    send_mail(
        'Ссылка для входа на сайт списков',
        f'Чтобы войти на сайт перейдите по ссылке: \n{url}',
        'al-fa-y@yandex.ru',
        [email]
    )
    messages.success(request, 'На вашу почту отправлена ссылка')

    return redirect('/')


def login(request):
    """вход пользователя по ссылке"""

    token = request.GET.get('token')
    user = auth.authenticate(uid=token)
    if user:
        auth.login(request, user)
    return redirect('/')

superlists/lists/views.py
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from lists.forms import ItemForm, ExistingListItemForm, NewListForm
from lists.models import Item, List

User = get_user_model()


def home_page(request):
    """домашняя страница"""

    return render(request, 'home.html', {'form': ItemForm()})


def view_list(request, list_id):
    """представление списка"""
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)
    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)

    return render(request, 'list.html', {'list': list_, 'form': form})


def new_list(request):
    """новый список 2"""

    form = NewListForm(data=request.POST)

    if form.is_valid():
        list_ = form.save(owner=request.user)
        return redirect(list_)

    return render(request, 'home.html', {'form': form})


def my_lists(request, email):
    """мои списки"""

    owner = User.objects.get(email=email)
    return render(request, 'my_lists.html', {'owner': owner})


def share_list(request, list_id):
    """поделиться списком"""
    email = request.POST.get('sharee')
    list_ = List.objects.get(id=list_id)
    user = User.objects.filter(email=email).first()
    print(email, user, list_)
    if user:
        list_.shared_with.add(user)
    return redirect(list_)

superlists/accounts/templates/login_email_sent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Email sent</h1>
<p>На вашу почту отправлена ссылка для входа на сайт.</p>

</body>
</html>

superlists/lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/base.css" rel="stylesheet">
</head>

<body>
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Списки</a>
            {% if user.email %}
                <ul class="nav navbar-nav navbar-right">
                    <li class="navbar-text">Вы вошли как {{ user.email }}</li>
                    <li><a href="{% url 'my_lists' user.email %}">Мои списки</a></li>
                    <li><a href="{% url 'logout' %}">Выйти</a></li>
                </ul>
            {% else %}
                <form class="navbar-form navbar-right" method="POST" action="{% url 'send_login_email' %}">
                    <span>Введите email для входа:</span>
                    <input class="form-control" name="email" type="text"/>
                    {% csrf_token %}
                </form>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
        <div class="row">
            <div class="col-md-8">
                {% for message in messages %}
                    {% if message.level_tag == 'success' %}
                        <div class="alert alert-success">{{ message }}</div>
                    {% else %}
                        <div class="alert alert-warning">{{ message }}</div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    {% endif %}


    <div class="row">
        <div class="col-md-6 col-md-offset-3 jumbotron">
            <div class="text-center">
                <h1>{% block header_text %}{% endblock %}</h1>
                {% block list_form %}
                    <form method="POST" action="{% block form_action %}{% endblock %}">
                        {{ form.text }}
                        {% csrf_token %}
                        {% if form.errors %}
                            <div class="form-group has-error">
                                <span class="help-block">{{ form.errors }}</span>
                            </div>
                        {% endif %}
                    </form>
                {% endblock %}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {% block table %}
            {% endblock %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {% block extra_content %}
            {% endblock %}
        </div>
    </div>
</div>
<script src="/static/jquery-3.4.1.js"></script>
<script src="/static/list.js"></script>
<script>
    $(document).ready(function () {
        window.Superlists.initialize();
    });

</script>
</body>

</html>

superlists/lists/templates/home.html
{% extends 'base.html' %}
{% block title %}To-DO{% endblock %}
{% block header_text %}Start a new to-do list{% endblock %}
{% block form_action %}{% url 'new_list' %}{% endblock %}

superlists/lists/templates/list.html
{% extends 'base.html' %}
{% block title %}To-DO{% endblock %}
{% block header_text %}Your To-Do list{% endblock %}
{% block form_action %}{% url 'view_list' list.id %}{% endblock %}
{% block table %}
    <table id="id_list_table" class="table">
        {% for item in list.item_set.all %}
            <tr>
                <td>{{ forloop.counter }}: {{ item.text }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

{% block extra_content %}

    <div class="col-xs-6">
        <h4>Поделиться списком</h4>
        <form action="{% url "share_list" list.id %}" method="post">
            {% csrf_token %}
            <input name="sharee" type="email" placeholder="your-friend@example.com">
        </form>
    </div>
    <div class="col-xs-6">
        <h4>Список доступен для:</h4>
        <ul>
            {% for user in list.shared_with.all %}
                <li>{{ user.email }}</li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

superlists/lists/templates/my_lists.html
{% extends 'base.html' %}

{% block header_text %} Мои списки {% endblock %}

{% block list_form %}{% endblock %}

{% block extra_content %}
    <div class="col-xs-6">
        <h4>Доступные вам</h4>
        <ul>
            {% for list in owner.available_lists.all %}
                <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-xs-6">
        <h4>Ваши списки</h4>
        <ul>
            {% for list in owner.list_set.all %}
                <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}